# pm2 config
# https://pm2.keymetrics.io/docs/usage/application-declaration/#attributes-available

apps:
  - name: floofy-bot
    script: ./dist/index.js
    node_args: --env-file=.env
    env:
      # Makes `npm ci` omit dev dependencies
      NODE_ENV: production
